version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  nodejs:
    docker:
      - image: 'circleci/node:latest'
      - image: 'mongo:4.2.5-bionic'
# extraneous key [port] is not permitted
#        port: 27017:27017
# extraneous key [ports] is not permitted
#        ports:
#          - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongoadmin
          MONGO_INITDB_ROOT_PASSWORD: p@ssw0rdToYourMom
    steps:
      - checkout
      - run:
          command: |
            cd node
            ssh-keygen -t rsa -b 4096 -C "fake@email.org" -f ./verbal_rsa -q -N ""
            npm install
            npm run test_ci
      - slack/status:
          fail_only: true
  react:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          command: |
            cd react
            npm install
            npm run build
      - slack/status:
          fail_only: true   
  deploy:
    machine:
      enabled: true
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          command: |
            cd util
            . ./app-container.sh $CIRCLE_BUILD_NUM
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push verbalwebsites/rrk9_store:$(cat ../version)-${CIRCLE_BUILD_NUM}
      - slack/status:
          fail_only: false
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - nodejs
      - react:
          requires:
            - nodejs
      - deploy:
          requires:
            - react
