version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  dropwizard:
    docker:
      - image: 'circleci/openjdk:14-buster'
      - image: 'postgres:9.6-alpine'
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: passw0rD!
          POSTGRES_DB: rrk9_store
    steps:
      - checkout
      - run:
          command: |
            cd java
            ssh-keygen -t rsa -b 4096 -C "fake@email.org" -f ./verbal_rsa -q -N ""
            mvn clean install
            java -jar target/rrk9-store-1.0.jar server rrk9.yml
      - slack/status:
          fail_only: true
  react:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          command: |
            cd react
            printf "%s\n" "REACT_APP_SANDBOX_CLIENT_ID=${REACT_APP_SANDBOX_CLIENT_ID}" "REACT_APP_PRODUCTION_CLIENT_ID=${REACT_APP_PRODUCTION_CLIENT_ID}" >> .env.development
            npm install
            npm run test_ci
      - slack/status:
          fail_only: true   
  deploy:
    machine:
      enabled: true
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          command: |
            printf "%s\n" "REACT_APP_SANDBOX_CLIENT_ID=${REACT_APP_SANDBOX_CLIENT_ID}" "REACT_APP_PRODUCTION_CLIENT_ID=${REACT_APP_PRODUCTION_CLIENT_ID}" >> react/.env.production
            cd util
            . ./app-container.sh $CIRCLE_BUILD_NUM
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push verbalwebsites/rrk9_store
      - slack/status:
          fail_only: false
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - nodejs
      - react:
          requires:
            - nodejs
      - deploy:
          requires:
            - react
