version: 2.1
jobs:
  nodejs:
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/mongodb:latest'
    steps:
      - checkout
      - run:
          command: |
            cd node
            npm install
            npm build
            npm run start
  react:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          command: |
            cd react
            npm install
            npm build
#           npm test
workflows:
  build-and-test:
    jobs:
      - nodejs
      - react
