version: 2.1
jobs:
  nodejs:
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/mongo:latest'
    steps:
      - checkout
      - run:
          command: |
            cd node
            ssh-keygen -t rsa -b 4096 -C "fake@email.org" -f ./verbal_rsa -q -N ""
            npm install
            npm build
            npm run start
  react:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          command: |
            cd react
            npm install
            npm build
workflows:
  build-and-test:
    jobs:
      - nodejs
      - react
